.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. rhombus_qt test_particl_qt
clean: FORCE
	$(MAKE) -C .. rhombus_qt_clean test_particl_qt_clean
check: FORCE
	$(MAKE) -C .. test_rhombus_qt_check
bitcoin-qt bitcoin-qt.exe: FORCE
	 $(MAKE) -C .. rhombus_qt
